### ISSUE TITLE
v24 Proto Checklist Issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/MP3_Trigger#1]
(1) Sheet 2 needs a frame

(2) 7 4-way jumpers in sheet 2

(3) Dashed lines in SCH are on "Symbols" instead of "Info"

(4) LM1117 had wrong prefix

(5) Board "Dimension" outline is 10mil instead of 8mil

(6) I updated my Eagle_rules repo and loaded it into the design, it seemed to fix the via sizing issue. I'm think the DRU in the project is just outdated

(7) When the vias changed it threw a Clearance error/issue

(8) Need measures in BRD

(9) 1.8V vreg needs silk for footprint

that's it!

**Comment by JoelEB** [comment]
(1) Sheet 2 needs a frame - Fixed

(2) 7 4-way jumpers in sheet 2 - Fixed

(3) Dashed lines in SCH are on "Symbols" instead of "Info" - Fixed

(4) LM1117 had wrong prefix - Changed to U4

(5) Board "Dimension" outline is 10mil instead of 8mil - Fixed

(6) I updated my Eagle_rules repo and loaded it into the design, it seemed to fix the via sizing issue. I'm think the DRU in the project is just outdated 

(7) When the vias changed it threw a Clearance error/issue - Non-issue

(8) Need measures in BRD - Added

(9) 1.8V vreg needs silk for footprint - Added and synced
